# Generated by Django 4.1.5 on 2023-02-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('detail', models.TextField(max_length=255)),
                ('completed', models.BooleanField(default=True)),
            ],
        ),
    ]
